export interface Country {
  name: string;
  code: string;
  dial: string;
  flag: string;
  minLength: number;
  maxLength: number;
}

export const COUNTRIES: Country[] = [
  {
    name: "Nigeria",
    code: "NG",
    dial: "+234",
    flag: "🇳🇬",
    minLength: 10,
    maxLength: 11,
  },
  {
    name: "Ghana",
    code: "GH",
    dial: "+233",
    flag: "🇬🇭",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Kenya",
    code: "KE",
    dial: "+254",
    flag: "🇰🇪",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "South Africa",
    code: "ZA",
    dial: "+27",
    flag: "🇿🇦",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Tanzania",
    code: "TZ",
    dial: "+255",
    flag: "🇹🇿",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Uganda",
    code: "UG",
    dial: "+256",
    flag: "🇺🇬",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Ethiopia",
    code: "ET",
    dial: "+251",
    flag: "🇪🇹",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Cameroon",
    code: "CM",
    dial: "+237",
    flag: "🇨🇲",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Senegal",
    code: "SN",
    dial: "+221",
    flag: "🇸🇳",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Côte d'Ivoire",
    code: "CI",
    dial: "+225",
    flag: "🇨🇮",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Rwanda",
    code: "RW",
    dial: "+250",
    flag: "🇷🇼",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Zambia",
    code: "ZM",
    dial: "+260",
    flag: "🇿🇲",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Malawi",
    code: "MW",
    dial: "+265",
    flag: "🇲🇼",
    minLength: 7,
    maxLength: 9,
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    dial: "+263",
    flag: "🇿🇼",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Egypt",
    code: "EG",
    dial: "+20",
    flag: "🇪🇬",
    minLength: 10,
    maxLength: 11,
  },
  {
    name: "Morocco",
    code: "MA",
    dial: "+212",
    flag: "🇲🇦",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Algeria",
    code: "DZ",
    dial: "+213",
    flag: "🇩🇿",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Angola",
    code: "AO",
    dial: "+244",
    flag: "🇦🇴",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Benin",
    code: "BJ",
    dial: "+229",
    flag: "🇧🇯",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Botswana",
    code: "BW",
    dial: "+267",
    flag: "🇧🇼",
    minLength: 7,
    maxLength: 8,
  },
  {
    name: "Burkina Faso",
    code: "BF",
    dial: "+226",
    flag: "🇧🇫",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Burundi",
    code: "BI",
    dial: "+257",
    flag: "🇧🇮",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Cape Verde",
    code: "CV",
    dial: "+238",
    flag: "🇨🇻",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Central African Republic",
    code: "CF",
    dial: "+236",
    flag: "🇨🇫",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Chad",
    code: "TD",
    dial: "+235",
    flag: "🇹🇩",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Comoros",
    code: "KM",
    dial: "+269",
    flag: "🇰🇲",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Congo (DRC)",
    code: "CD",
    dial: "+243",
    flag: "🇨🇩",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Congo (Republic)",
    code: "CG",
    dial: "+242",
    flag: "🇨🇬",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Djibouti",
    code: "DJ",
    dial: "+253",
    flag: "🇩🇯",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    dial: "+240",
    flag: "🇬🇶",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Eritrea",
    code: "ER",
    dial: "+291",
    flag: "🇪🇷",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Eswatini",
    code: "SZ",
    dial: "+268",
    flag: "🇸🇿",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Gabon",
    code: "GA",
    dial: "+241",
    flag: "🇬🇦",
    minLength: 7,
    maxLength: 8,
  },
  {
    name: "Gambia",
    code: "GM",
    dial: "+220",
    flag: "🇬🇲",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Guinea",
    code: "GN",
    dial: "+224",
    flag: "🇬🇳",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    dial: "+245",
    flag: "🇬🇼",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Lesotho",
    code: "LS",
    dial: "+266",
    flag: "🇱🇸",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Liberia",
    code: "LR",
    dial: "+231",
    flag: "🇱🇷",
    minLength: 7,
    maxLength: 9,
  },
  {
    name: "Libya",
    code: "LY",
    dial: "+218",
    flag: "🇱🇾",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Madagascar",
    code: "MG",
    dial: "+261",
    flag: "🇲🇬",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Mali",
    code: "ML",
    dial: "+223",
    flag: "🇲🇱",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Mauritania",
    code: "MR",
    dial: "+222",
    flag: "🇲🇷",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Mauritius",
    code: "MU",
    dial: "+230",
    flag: "🇲🇺",
    minLength: 7,
    maxLength: 8,
  },
  {
    name: "Mozambique",
    code: "MZ",
    dial: "+258",
    flag: "🇲🇿",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Namibia",
    code: "NA",
    dial: "+264",
    flag: "🇳🇦",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Niger",
    code: "NE",
    dial: "+227",
    flag: "🇳🇪",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Sierra Leone",
    code: "SL",
    dial: "+232",
    flag: "🇸🇱",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Somalia",
    code: "SO",
    dial: "+252",
    flag: "🇸🇴",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "South Sudan",
    code: "SS",
    dial: "+211",
    flag: "🇸🇸",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Sudan",
    code: "SD",
    dial: "+249",
    flag: "🇸🇩",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "São Tomé & Príncipe",
    code: "ST",
    dial: "+239",
    flag: "🇸🇹",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Seychelles",
    code: "SC",
    dial: "+248",
    flag: "🇸🇨",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Togo",
    code: "TG",
    dial: "+228",
    flag: "🇹🇬",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Tunisia",
    code: "TN",
    dial: "+216",
    flag: "🇹🇳",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Zanzibar",
    code: "ZZ",
    dial: "+255",
    flag: "🇿🇼",
    minLength: 9,
    maxLength: 10,
  },
];

/** Strip leading zero and return digits only */
export function normalizeLocalNumber(input: string): string {
  const digits = input.replace(/\D/g, "");
  return digits.startsWith("0") ? digits.slice(1) : digits;
}

/** Build full E.164 phone number from country + local input */
export function buildFullPhone(country: Country, localNumber: string): string {
  return `${country.dial}${normalizeLocalNumber(localNumber)}`;
}

/** Validate that the local number (after stripping 0) is within length bounds */
export function validatePhone(
  country: Country,
  localNumber: string
): string | null {
  const normalized = normalizeLocalNumber(localNumber);
  if (normalized.length === 0) {
    return "Phone number is required";
  }
  if (
    normalized.length < country.minLength - 1 ||
    normalized.length > country.maxLength
  ) {
    return `Enter ${country.minLength - 1}–${country.maxLength} digits for ${country.name}`;
  }
  return null;
}
