export interface Country {
  name: string;
  code: string;
  dial: string;
  minLength: number;
  maxLength: number;
}

export const COUNTRIES: Country[] = [
  { name: "Nigeria", code: "NG", dial: "+234", minLength: 10, maxLength: 11 },
  { name: "Ghana", code: "GH", dial: "+233", minLength: 9, maxLength: 10 },
  { name: "Kenya", code: "KE", dial: "+254", minLength: 9, maxLength: 10 },
  {
    name: "South Africa",
    code: "ZA",
    dial: "+27",
    minLength: 9,
    maxLength: 10,
  },
  { name: "Tanzania", code: "TZ", dial: "+255", minLength: 9, maxLength: 10 },
  { name: "Uganda", code: "UG", dial: "+256", minLength: 9, maxLength: 10 },
  { name: "Ethiopia", code: "ET", dial: "+251", minLength: 9, maxLength: 9 },
  { name: "Cameroon", code: "CM", dial: "+237", minLength: 8, maxLength: 9 },
  { name: "Senegal", code: "SN", dial: "+221", minLength: 9, maxLength: 9 },
  {
    name: "Cote d'Ivoire",
    code: "CI",
    dial: "+225",
    minLength: 10,
    maxLength: 10,
  },
  { name: "Rwanda", code: "RW", dial: "+250", minLength: 9, maxLength: 9 },
  { name: "Zambia", code: "ZM", dial: "+260", minLength: 9, maxLength: 10 },
  { name: "Malawi", code: "MW", dial: "+265", minLength: 7, maxLength: 9 },
  { name: "Zimbabwe", code: "ZW", dial: "+263", minLength: 9, maxLength: 10 },
  { name: "Egypt", code: "EG", dial: "+20", minLength: 10, maxLength: 11 },
  { name: "Morocco", code: "MA", dial: "+212", minLength: 9, maxLength: 9 },
  { name: "Algeria", code: "DZ", dial: "+213", minLength: 9, maxLength: 9 },
  { name: "Angola", code: "AO", dial: "+244", minLength: 9, maxLength: 9 },
  { name: "Benin", code: "BJ", dial: "+229", minLength: 8, maxLength: 8 },
  { name: "Botswana", code: "BW", dial: "+267", minLength: 7, maxLength: 8 },
  {
    name: "Burkina Faso",
    code: "BF",
    dial: "+226",
    minLength: 8,
    maxLength: 8,
  },
  { name: "Burundi", code: "BI", dial: "+257", minLength: 8, maxLength: 8 },
  {
    name: "Cape Verde",
    code: "CV",
    dial: "+238",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Central African Republic",
    code: "CF",
    dial: "+236",
    minLength: 8,
    maxLength: 8,
  },
  { name: "Chad", code: "TD", dial: "+235", minLength: 8, maxLength: 8 },
  { name: "Comoros", code: "KM", dial: "+269", minLength: 7, maxLength: 7 },
  {
    name: "Congo (DRC)",
    code: "CD",
    dial: "+243",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Congo (Republic)",
    code: "CG",
    dial: "+242",
    minLength: 9,
    maxLength: 9,
  },
  { name: "Djibouti", code: "DJ", dial: "+253", minLength: 8, maxLength: 8 },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    dial: "+240",
    minLength: 9,
    maxLength: 9,
  },
  { name: "Eritrea", code: "ER", dial: "+291", minLength: 7, maxLength: 7 },
  { name: "Eswatini", code: "SZ", dial: "+268", minLength: 8, maxLength: 8 },
  { name: "Gabon", code: "GA", dial: "+241", minLength: 7, maxLength: 8 },
  { name: "Gambia", code: "GM", dial: "+220", minLength: 7, maxLength: 7 },
  { name: "Guinea", code: "GN", dial: "+224", minLength: 8, maxLength: 9 },
  {
    name: "Guinea-Bissau",
    code: "GW",
    dial: "+245",
    minLength: 7,
    maxLength: 7,
  },
  { name: "Lesotho", code: "LS", dial: "+266", minLength: 8, maxLength: 8 },
  { name: "Liberia", code: "LR", dial: "+231", minLength: 7, maxLength: 9 },
  { name: "Libya", code: "LY", dial: "+218", minLength: 9, maxLength: 9 },
  { name: "Madagascar", code: "MG", dial: "+261", minLength: 9, maxLength: 9 },
  { name: "Mali", code: "ML", dial: "+223", minLength: 8, maxLength: 8 },
  { name: "Mauritania", code: "MR", dial: "+222", minLength: 8, maxLength: 8 },
  { name: "Mauritius", code: "MU", dial: "+230", minLength: 7, maxLength: 8 },
  { name: "Mozambique", code: "MZ", dial: "+258", minLength: 9, maxLength: 9 },
  { name: "Namibia", code: "NA", dial: "+264", minLength: 9, maxLength: 9 },
  { name: "Niger", code: "NE", dial: "+227", minLength: 8, maxLength: 8 },
  {
    name: "Sierra Leone",
    code: "SL",
    dial: "+232",
    minLength: 8,
    maxLength: 8,
  },
  { name: "Somalia", code: "SO", dial: "+252", minLength: 8, maxLength: 9 },
  {
    name: "South Sudan",
    code: "SS",
    dial: "+211",
    minLength: 9,
    maxLength: 9,
  },
  { name: "Sudan", code: "SD", dial: "+249", minLength: 9, maxLength: 9 },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    dial: "+239",
    minLength: 7,
    maxLength: 7,
  },
  { name: "Seychelles", code: "SC", dial: "+248", minLength: 7, maxLength: 7 },
  { name: "Togo", code: "TG", dial: "+228", minLength: 8, maxLength: 8 },
  { name: "Tunisia", code: "TN", dial: "+216", minLength: 8, maxLength: 8 },
];
